### ISSUE TITLE
speaker embedding npy file not found

### ISSUE THREAD

**Issue by raikarsagar** [keonlee9420/Cross-Speaker-Emotion-Transfer#6]
Hi,

I am facing the following issue while synthesizing using pretrained model.

Removing weight norm...
Traceback (most recent call last):
  File "synthesize.py", line 234, in <module>
    )) if load_spker_embed else None
  File "/home/sagar/tts/Cross-Speaker-Emotion-Transfer/venv/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './preprocessed_data/RAVDESS/spker_embed/Actor_19-spker_embed.npy'

Please suggest any way out. Thanks in advance
-Sagar

**Comment by PS-AI** [comment]
Yes, I'm facing the same problem too. Any help with this will be appreciated.

**Comment by keonlee9420** [comment]
Hi guys, thanks for your attention. You have to prepare `spker_embed/` first following README.md. But I just shared it [here](https://drive.google.com/drive/folders/1a4YW2UWdlF9RTqG_phv_VbRjyEcAld7t?usp=sharing) for your convenience, so please check it out. 3

**Comment by raikarsagar** [comment]
@keonlee9420  Could you please point me to the documentation for preparing `spker_embed` ? I couldnt find instructions in main branch readme.

**Comment by keonlee9420** [comment]
You can get it during [preprocessing](https://github.com/keonlee9420/Cross-Speaker-Emotion-Transfer#preprocessing).

**Comment by CrackerHax** [comment]
python3 preprocess.py --dataset RAVDESS give errors:
```
Cross-Speaker-Emotion-Transfer/audio/stft.py:145: FutureWarning: Pass sr=22050, n_fft=1024, n_mels=80, fmin=0, fmax=8000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel_basis = librosa_mel_fn(
Load pre-defined validation set...
2022-08-15 15:19:21.878700: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:961] could not open file to read NUMA node: /sys/bus/pci/devices/0000:0b:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-08-15 15:19:22.444754: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.3/lib64
2022-08-15 15:19:22.444795: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2022-08-15 15:19:22.445092: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Processing Data ...
0it [00:00, ?it/s]
Total time: 0.0 hours
Plot speaker embedding...
0it [00:00, ?it/s]
25it [00:00, 62009.23it/s]
/usr/local/lib/python3.8/dist-packages/sklearn/manifold/_t_sne.py:805: FutureWarning: The default learning rate in TSNE will change from 200.0 to 'auto' in 1.2.
  warnings.warn(
Traceback (most recent call last):
  File "preprocess.py", line 20, in <module>
    preprocessor.build_from_path()
  File "/mnt/e/ai/src/Cross-Speaker-Emotion-Transfer/preprocessor/preprocessor.py", line 153, in build_from_path
    plot_embedding(
  File "/mnt/e/ai/src/Cross-Speaker-Emotion-Transfer/utils/tools.py", line 262, in plot_embedding
    tsne_all_data = tsne_model.fit_transform(data_x)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/manifold/_t_sne.py", line 1117, in fit_transform
    embedding = self._fit(X)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/manifold/_t_sne.py", line 838, in _fit
    X = self._validate_data(
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 577, in _validate_data
    X = check_array(X, input_name="X", **check_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 871, in check_array
    raise ValueError(
ValueError: Expected 2D array, got scalar array instead:
array=nan.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
```
